name: SolarBeatz
favicon: null
layout_spectrum: 0.74529
typography_spectrum: 0.8030415687244385
title: SolarBeatz
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#FF6700'
    - '#EBEBEB'
    - '#C0C0C0'
    - '#3A6EA5'
    - '#004E98'
  brandStrength: 0.05886083049699664
  lightness: 0.6475190015044063
  saturation: 0.9065975360572338
  rhythmicContrast: 0.22091594198718667
purpose: []
