name: SolarBeatz
favicon: null
layout_spectrum: 1
typography_spectrum: 0.8030415687244385
title: SolarBeatz
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#101417'
    - '#313a41'
    - '#999a95'
    - '#fdc800'
    - '#af502b'
  brandStrength: 0.875
  lightness: 0.125
  saturation: 0.9065975360572338
  rhythmicContrast: 0.25
purpose: []
