name: SolarBeatz
favicon: null
layout_spectrum: 1
typography_spectrum: 0.07465
title: 'Fire breathing mobile solar powered sound stage!?!?'
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#100f15'
    - '#768797'
    - '#462c5c'
    - '#dcded9'
    - '#f9bf74'
  brandStrength: 0.875
  lightness: 0.125
  saturation: 0.5
  rhythmicContrast: 0.25
purpose: []
